import type {
  AnalyticsPoint,
  Bakery,
  DietaryOption,
  Filling,
  FlavorOption,
  Order,
  Product,
  Review,
  SizeOption,
  Topping,
} from '@shared/types';

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`;

export const bakeries: Bakery[] = [
  {
    id: 'b1',
    slug: 'olive-and-oak',
    name: 'Olive & Oak Bakery',
    cover: img('photo-1486427944299-d1955d23e34d'),
    rating: 4.9,
    reviews: 1284,
    deliveryMinutes: 35,
    city: 'Kololo, Kampala',
    tags: ['Custom Cakes', 'Vegan'],
    featured: true,
  },
  {
    id: 'b2',
    slug: 'sugarbloom',
    name: 'Sugarbloom Patisserie',
    cover: img('photo-1599785209707-a456fc1337bb'),
    rating: 4.8,
    reviews: 982,
    deliveryMinutes: 45,
    city: 'Naguru, Kampala',
    tags: ['Pastry', 'French'],
    featured: true,
  },
  {
    id: 'b3',
    slug: 'maple-and-honey',
    name: 'Maple & Honey',
    cover: img('photo-1565958011703-44f9829ba187'),
    rating: 4.7,
    reviews: 642,
    deliveryMinutes: 25,
    city: 'Entebbe',
    tags: ['Cupcakes', 'Gluten-Free'],
  },
  {
    id: 'b4',
    slug: 'crumb-and-co',
    name: 'Crumb & Co.',
    cover: img('photo-1464195244916-405fa0a82545'),
    rating: 4.9,
    reviews: 2104,
    deliveryMinutes: 30,
    city: 'Bugolobi, Kampala',
    tags: ['Wedding', 'Custom'],
    featured: true,
  },
  {
    id: 'b5',
    slug: 'velvet-crown',
    name: 'Velvet Crown',
    cover: img('photo-1535141192574-5d4897c12636'),
    rating: 4.6,
    reviews: 318,
    deliveryMinutes: 40,
    city: 'Jinja',
    tags: ['Red Velvet', 'Cheesecake'],
  },
  {
    id: 'b6',
    slug: 'pearl-and-pistachio',
    name: 'Pearl & Pistachio',
    cover: img('photo-1488477181946-6428a0291777'),
    rating: 4.8,
    reviews: 451,
    deliveryMinutes: 50,
    city: 'Ntinda, Kampala',
    tags: ['Mediterranean', 'Pistachio'],
  },
];

export const products: Product[] = [
  {
    id: 'p1',
    bakeryId: 'b1',
    name: 'Midnight Chocolate Drip',
    description:
      'Triple-layer dark cocoa sponge with whipped ganache, fresh berries, and a hand-piped chocolate shell.',
    basePrice: 240000,
    image: img('photo-1578985545062-69928b1d9587'),
    rating: 4.9,
    reviews: 421,
    category: 'cake',
    tags: ['bestseller', 'chocolate'],
    preparationHours: 6,
    customizable: true,
    allergens: ['dairy', 'eggs', 'gluten'],
  },
  {
    id: 'p2',
    bakeryId: 'b2',
    name: 'Strawberry Garden',
    description:
      'Vanilla bean sponge layered with strawberry compote, finished with mascarpone cream and edible flowers.',
    basePrice: 215000,
    image: img('photo-1565958011703-44f9829ba187'),
    rating: 4.8,
    reviews: 312,
    category: 'cake',
    tags: ['seasonal', 'fruit'],
    preparationHours: 5,
    customizable: true,
    allergens: ['dairy', 'eggs', 'gluten'],
  },
  {
    id: 'p3',
    bakeryId: 'b3',
    name: 'Honey Pistachio Bloom',
    description:
      'Light pistachio sponge brushed with orange blossom syrup, topped with whipped honey buttercream.',
    basePrice: 265000,
    image: img('photo-1571115177098-24ec42ed204d'),
    rating: 4.9,
    reviews: 256,
    category: 'cake',
    tags: ['nut-free option', 'mediterranean'],
    preparationHours: 7,
    customizable: true,
    allergens: ['dairy', 'eggs', 'nuts'],
  },
  {
    id: 'p4',
    bakeryId: 'b4',
    name: 'Wild Berry Tower',
    description:
      'Three-tier vanilla cake stacked with fresh raspberries, blackberries, and Italian buttercream.',
    basePrice: 460000,
    image: img('photo-1464195244916-405fa0a82545'),
    rating: 4.9,
    reviews: 173,
    category: 'cake',
    tags: ['celebration', 'multi-tier'],
    preparationHours: 12,
    customizable: true,
    allergens: ['dairy', 'eggs', 'gluten'],
  },
  {
    id: 'p5',
    bakeryId: 'b5',
    name: 'Classic Red Velvet',
    description:
      'Velvety red sponge with cream cheese frosting and white chocolate curls.',
    basePrice: 180000,
    image: img('photo-1535141192574-5d4897c12636'),
    rating: 4.7,
    reviews: 489,
    category: 'cake',
    tags: ['classic', 'red velvet'],
    preparationHours: 4,
    customizable: true,
    allergens: ['dairy', 'eggs', 'gluten'],
  },
  {
    id: 'p6',
    bakeryId: 'b1',
    name: 'Hazelnut Praline',
    description:
      'Roasted hazelnut sponge with praline crunch and milk chocolate ganache.',
    basePrice: 250000,
    image: img('photo-1606890737304-57a1ca8a5b62'),
    rating: 4.8,
    reviews: 211,
    category: 'cake',
    tags: ['nut', 'chocolate'],
    preparationHours: 6,
    customizable: true,
    allergens: ['nuts', 'dairy', 'eggs'],
  },
  {
    id: 'p7',
    bakeryId: 'b2',
    name: 'Lemon Lavender',
    description:
      'Citrusy lemon sponge with lavender-infused buttercream and candied lemon peel.',
    basePrice: 200000,
    image: img('photo-1519869325930-281384150729'),
    rating: 4.7,
    reviews: 198,
    category: 'cake',
    tags: ['floral', 'citrus'],
    preparationHours: 5,
    customizable: true,
    allergens: ['dairy', 'eggs', 'gluten'],
  },
  {
    id: 'p8',
    bakeryId: 'b6',
    name: 'Tiramisu Dream',
    description:
      'Espresso-soaked ladyfingers, mascarpone cream, and a dusting of dark cocoa.',
    basePrice: 230000,
    image: img('photo-1626803775151-61d756612f97'),
    rating: 4.9,
    reviews: 267,
    category: 'cake',
    tags: ['italian', 'coffee'],
    preparationHours: 6,
    customizable: false,
    allergens: ['dairy', 'eggs', 'gluten'],
  },
];

export const sizeOptions: SizeOption[] = [
  { id: 's-6', label: '6"', serves: 'Serves 6–8', priceMultiplier: 1 },
  { id: 's-8', label: '8"', serves: 'Serves 10–12', priceMultiplier: 1.35 },
  { id: 's-10', label: '10"', serves: 'Serves 16–20', priceMultiplier: 1.7 },
  { id: 's-12', label: '12"', serves: 'Serves 24–30', priceMultiplier: 2.1 },
];

export const flavorOptions: FlavorOption[] = [
  { id: 'f-choc', name: 'Dark Chocolate', description: 'Rich, deep cocoa sponge' },
  { id: 'f-vanilla', name: 'Vanilla Bean', description: 'Madagascar vanilla' },
  { id: 'f-redvelvet', name: 'Red Velvet', description: 'Buttermilk classic', priceDelta: 15000 },
  { id: 'f-strawberry', name: 'Strawberry', description: 'Fresh strawberry purée' },
  { id: 'f-matcha', name: 'Matcha Green Tea', description: 'Stone-ground matcha', priceDelta: 22000 },
];

export const fillingOptions: Filling[] = [
  { id: 'fl-ganache', name: 'Chocolate Ganache', price: 15000 },
  { id: 'fl-strawberry', name: 'Strawberry Jam', price: 12000 },
  { id: 'fl-vanilla', name: 'Vanilla Buttercream', price: 12000 },
  { id: 'fl-caramel', name: 'Salted Caramel', price: 18000 },
  { id: 'fl-creamcheese', name: 'Cream Cheese', price: 15000 },
  { id: 'fl-praline', name: 'Hazelnut Praline', price: 22000 },
];

export const toppingOptions: Topping[] = [
  { id: 't-strawberry', name: 'Fresh Strawberries', price: 18000, emoji: '🍓' },
  { id: 't-cherry', name: 'Cherries', price: 15000, emoji: '🍒' },
  { id: 't-blueberry', name: 'Blueberries', price: 15000, emoji: '🫐' },
  { id: 't-chocolate', name: 'Chocolate Shards', price: 18000, emoji: '🍫' },
  { id: 't-sprinkles', name: 'Rainbow Sprinkles', price: 8000, emoji: '🌈' },
  { id: 't-candle', name: 'Birthday Candle', price: 4000, emoji: '🕯️' },
];

export const dietaryOptions: DietaryOption[] = [
  { id: 'd-gluten-free', label: 'Gluten Free' },
  { id: 'd-dairy-free', label: 'Dairy Free', conflicts: ['fl-creamcheese', 'fl-vanilla', 'fl-ganache'] },
  { id: 'd-nut-free', label: 'Nut Free', conflicts: ['fl-praline'] },
  { id: 'd-vegan', label: 'Vegan', conflicts: ['fl-creamcheese', 'fl-ganache', 'fl-vanilla', 'fl-praline'] },
  { id: 'd-egg-free', label: 'Egg Free' },
  { id: 'd-keto', label: 'Keto Friendly' },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    author: 'Maya R.',
    rating: 5,
    comment:
      'The chocolate drip cake was a showstopper at our anniversary dinner. The team customized it perfectly.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: 'r2',
    author: 'Daniel K.',
    rating: 5,
    comment: "Eden's CrunchBox is now my go-to for last-minute celebration cakes. Tracking is fantastic.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
  },
  {
    id: 'r3',
    author: 'Priya S.',
    rating: 4,
    comment: 'Beautiful presentation and the gluten-free option still tasted amazing.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
  },
];

export const orders: Order[] = [
  {
    id: 'o1',
    reference: 'SW-1042',
    customerName: 'Amara Bennett',
    bakeryId: 'b1',
    items: [
      {
        id: 'ci-1',
        productId: 'p1',
        bakeryId: 'b1',
        name: 'Midnight Chocolate Drip',
        image: products[0].image,
        quantity: 1,
        unitPrice: 290000,
      },
    ],
    subtotal: 290000,
    deliveryFee: 22000,
    discount: 30000,
    total: 282000,
    status: 'baking',
    placedAt: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
    estimatedReadyAt: new Date(Date.now() + 1000 * 60 * 90).toISOString(),
    address: 'Plot 14 Acacia Ave, Kololo, Kampala',
    paymentMethod: 'card',
    notes: 'Please write "Happy 30th Maya" in white frosting.',
    timeline: [
      { status: 'placed', at: new Date(Date.now() - 1000 * 60 * 32).toISOString() },
      { status: 'confirmed', at: new Date(Date.now() - 1000 * 60 * 26).toISOString() },
      { status: 'baking', at: new Date(Date.now() - 1000 * 60 * 12).toISOString() },
    ],
  },
  {
    id: 'o2',
    reference: 'SW-1041',
    customerName: 'Daniel Kim',
    bakeryId: 'b1',
    items: [
      {
        id: 'ci-2',
        productId: 'p7',
        bakeryId: 'b2',
        name: 'Lemon Lavender',
        image: products[6].image,
        quantity: 2,
        unitPrice: 200000,
      },
    ],
    subtotal: 400000,
    deliveryFee: 25000,
    discount: 0,
    total: 425000,
    status: 'confirmed',
    placedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    estimatedReadyAt: new Date(Date.now() + 1000 * 60 * 200).toISOString(),
    address: '6 Yusuf Lule Rd, Nakasero, Kampala',
    paymentMethod: 'mobile_money',
    timeline: [
      { status: 'placed', at: new Date(Date.now() - 1000 * 60 * 12).toISOString() },
      { status: 'confirmed', at: new Date(Date.now() - 1000 * 60 * 4).toISOString() },
    ],
  },
  {
    id: 'o3',
    reference: 'SW-1040',
    customerName: 'Priya Shah',
    bakeryId: 'b1',
    items: [
      {
        id: 'ci-3',
        productId: 'p4',
        bakeryId: 'b4',
        name: 'Wild Berry Tower',
        image: products[3].image,
        quantity: 1,
        unitPrice: 460000,
      },
    ],
    subtotal: 460000,
    deliveryFee: 30000,
    discount: 45000,
    total: 445000,
    status: 'ready',
    placedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    estimatedReadyAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    address: 'Plot 30 Lugogo Bypass, Naguru, Kampala',
    paymentMethod: 'card',
    timeline: [
      { status: 'placed', at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString() },
      { status: 'confirmed', at: new Date(Date.now() - 1000 * 60 * 60 * 3.5).toISOString() },
      { status: 'baking', at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString() },
      { status: 'ready', at: new Date(Date.now() - 1000 * 60 * 30).toISOString() },
    ],
  },
  {
    id: 'o4',
    reference: 'SW-1038',
    customerName: 'Liam Chen',
    bakeryId: 'b1',
    items: [
      {
        id: 'ci-4',
        productId: 'p2',
        bakeryId: 'b2',
        name: 'Strawberry Garden',
        image: products[1].image,
        quantity: 1,
        unitPrice: 215000,
      },
    ],
    subtotal: 215000,
    deliveryFee: 22000,
    discount: 0,
    total: 237000,
    status: 'placed',
    placedAt: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
    estimatedReadyAt: new Date(Date.now() + 1000 * 60 * 240).toISOString(),
    address: 'Plot 8 Mawanda Rd, Kamwokya, Kampala',
    paymentMethod: 'cash',
    timeline: [{ status: 'placed', at: new Date(Date.now() - 1000 * 60 * 4).toISOString() }],
  },
  {
    id: 'o5',
    reference: 'SW-1035',
    customerName: 'Zara Patel',
    bakeryId: 'b1',
    items: [
      {
        id: 'ci-5',
        productId: 'p5',
        bakeryId: 'b5',
        name: 'Classic Red Velvet',
        image: products[4].image,
        quantity: 1,
        unitPrice: 180000,
      },
    ],
    subtotal: 180000,
    deliveryFee: 18000,
    discount: 0,
    total: 198000,
    status: 'delivered',
    placedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    estimatedReadyAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    address: 'Plot 45 Tank Hill Rd, Muyenga, Kampala',
    paymentMethod: 'card',
    timeline: [
      { status: 'placed', at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
      { status: 'confirmed', at: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString() },
      { status: 'baking', at: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString() },
      { status: 'ready', at: new Date(Date.now() - 1000 * 60 * 60 * 21).toISOString() },
      { status: 'delivered', at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString() },
    ],
  },
];

export const revenueSeries: AnalyticsPoint[] = [
  { label: 'Mon', value: 4_600_000, secondary: 3_600_000 },
  { label: 'Tue', value: 6_900_000, secondary: 4_100_000 },
  { label: 'Wed', value: 7_800_000, secondary: 5_000_000 },
  { label: 'Thu', value: 6_400_000, secondary: 4_700_000 },
  { label: 'Fri', value: 9_900_000, secondary: 6_700_000 },
  { label: 'Sat', value: 11_600_000, secondary: 8_000_000 },
  { label: 'Sun', value: 10_600_000, secondary: 7_400_000 },
];

export const ordersByCategorySeries: AnalyticsPoint[] = [
  { label: 'Cakes', value: 412 },
  { label: 'Cupcakes', value: 286 },
  { label: 'Pastries', value: 198 },
  { label: 'Cookies', value: 124 },
  { label: 'Bread', value: 84 },
];

export const platformRevenueSeries: AnalyticsPoint[] = [
  { label: 'Jan', value: 91_000_000 },
  { label: 'Feb', value: 107_000_000 },
  { label: 'Mar', value: 115_000_000 },
  { label: 'Apr', value: 137_000_000 },
  { label: 'May', value: 152_000_000 },
  { label: 'Jun', value: 177_000_000 },
  { label: 'Jul', value: 193_000_000 },
  { label: 'Aug', value: 209_000_000 },
  { label: 'Sep', value: 229_000_000 },
  { label: 'Oct', value: 252_000_000 },
  { label: 'Nov', value: 268_000_000 },
  { label: 'Dec', value: 303_000_000 },
];
